version: 2.1

jobs:
  first-job:
    docker:
      - image: cimg/base:stable-18.04
    steps:
      - checkout
      - run:
          name: First Step
          command: pwd

  approval-job-1:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Approved by
          shell: /usr/local/bin/bash
          command: echo $CIRCLE_USERNAME

  approval-job-2:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Approved by
          shell: /usr/local/bin/bash
          command: echo $CIRCLE_USERNAME

  last-job:
    docker:
      - image: cimg/base:stable-18.04
    steps:
      - run:
          name: More steps
          command: pwd

workflows:
  my-workflow:
    jobs:
      - first-job
      - approval-1:
          type: approval
          requires:
            - first-job
      - approval-job-1:
          requires:
            - approval-1
          context: group-1
      - approval-2:
          type: approval
          requires:
            - first-job            
      - approval-job-2:
          requires:
            - approval-2
          context: group-2
      - last-job:
          requires:
            - approval-job-1
            - approval-job-2
