version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:2.7.4-node
    steps:
      - run:
          name: Current dir
          command: pwd

workflows:
  build-and-deploy:
    jobs:
      - approve:
          name: Approval Job
          type: approval
      - build:
          requires:
            - approve
          context: approval
